bluerobotics/ardusub-zola

- .github/workflows/action.yml
- .gitignore
- .gitmodules
- config.toml
- content/_index.md
- templates/docs/page.html
- templates/docs/section.html
- templates/macros/footer.html
- includes AdiDoks theme (my fork, to enable Zola >= 0.14)
- just the Docs part (no extra front page/Blog section)
- includes action to build
- TODO: delete `initial` branch once merged
> Clean initial setup

- configuration/index.md
It appears to be breaking current companion version, beta1
> configuration: Remove reset settings

- templates/docs/section.html
> templates: Improve section to work with the current structure

- installation.md
> installation: Update download link from 1.0.0.beta1 to 1.0.0.beta5

- .github/workflows/action.yml
> CI: Run deployment after 'Sync Submodules' action finishes

- _index.md
> index: Add extra.document_version

- installation.md
> installation: Update download link to 1.0.0-beta.14

- config.toml
- templates/docs/section.html
> Basic version support between submodules 

- .gitmodules
- content/software/companion/_index.md
- content/software/onboard/_index.md
- templates/docs/section.html
- change `Companion/1.0` to `Onboard Computer/BlueOS-1.0`
- update `companion-1.0` submodule to `BlueOS-1.0` (to match new branch name)
- fix #9
> Improve versioning, fix font

- templates/shortcodes/service.md
A shortcode for representing an underlying service and the port it's served at.
> shortcodes: create service.md

- .gitmodules
- content/software/autopilot/_index.md
Initial part of #50, just so #52 can become part of the public docs.
Merge after #52.
> Main ArduSub 4.1 Initial

- .gitmodules
- content/software/onboard/_index.md
- templates/docs/versions-section.html
- templates/shortcodes/easy_image.md
- currently redirecting individual pages
- see getzola/zola#2112 for future improvements
⚠️ **Do not merge before #47**
> Include BlueOS-1.1 docs

- advanced-usage/index.md
- Documents bluerobotics/BlueOS-docker#1512 (merge docs after feature)
> advanced-usage: Add information about zipped logs

- developers/log_messages.md
Relevant to #74 (provides the data for the current version, but does not yet provide a system to maintain it as the code changes).
> ArduSub 4.1 log messages

- developers/log_messages.md
> developers: DataFlash Logs: add useful links

- extensions/index.md
We're stoked there are companies being early adopters with this - it'd be nice to show them some love, while also providing some interesting examples for others to follow. Also good to show the most recent metadata in action :-)
> extensions: add more device-integration examples

- .gitmodules
- content/blueos/_index.md
- content/software/_index.md
- content/software/autopilot/_index.md
- content/software/onboard/_index.md
Relevant to [blueos.cloud/docs deployment](https://docs.google.com/document/d/1jhUnxJeVoJw_welrayZnvMTDyGO2a5YMevBYAiFhzs8/edit?usp=sharing)
> [BlueOS-deploy] content: reorganise for BlueOS focus

- _index.md
- overview/index.md
This branch is not yet being built into any docs, but given several of the main features are unlikely to disappear / change significantly in the near future it seems worthwhile starting to write down this info, to reduce the required documentation effort once it's actually release time.
> Cockpit: start docs

- installation.md
> [BlueOS-1.0] installation.md: fix broken relative link

- installation.md
> [BlueOS-1.1] installation.md: fix broken relative links

- development/bootstrap/index.md
- development/core/index.md
- development/overview/index.md
> [BlueOS 1.1] More development info

- development/extensions/index.md
Needed to jump an extra level up, since the file has been moved a level down.
Issue reported by G.
> development: extensions: fix broken relative links

- overview/index.md
Accessibility features are only useful if people know about them, so good to highlight them in the "What's New" section.
> overview: highlight styling accessibility benefit

- advanced-usage/index.md
Fix @rafaellehmkuhl's suggestions from #114
> advanced-usage: minor improvements

- development/extensions/index.md
Documents bluerobotics/BlueOS-Extensions-Repository#63 and bluerobotics/BlueOS#2080
> BlueOS: extensions: add `tool` type

- advanced-usage/index.md
Includes:
- change of widget name
- availability of new variables
- addition of the display name configuration
- addition of the fractional digits configuration
> Update docs for the new `VeryGenericIndicator`

- config.toml
- templates/base.html
> Add verification
