.gitmodules
content/software/_index.md
content/software/companion/_index.md

- Covers the existing companion 1 google doc (except the first page)
- Output at `docs.bluerobotics.com/ardusub-zola/software/companion/1.0`

Integrate Companion 1 Docs

---

_index.md

Docker is an implementation detail, and likely makes the name more confusing and 'scary' for users than it needs to be.

update name: BlueOS Docker -> BlueOS

---

advanced-usage/index.md

Forgot that Zola's `@` links need to be to a specific file.

advanced-usage: fix broken link

---

templates/shortcodes/mermaid.html

Absolute links need to use `base_url`, which is corrected for with the `get_url` macro.
Closes #44

templates: shortcodes: fix mermaid integration

---

getting-started/index.md

Old link is pointed to in BlueOS 1.0, so needs to redirect to the correct page in the current structure.

getting-started: add alias to old name/structure

---

advanced-usage/index.md

It was accidentally in the `[extra]` section, which doesn't work.

BlueOS-1.1: advanced-usage: fix broken alias

---

extensions/index.md

Minor fixes and improvements.
Main fix is to the currently incorrect description for `authors`.

extensions: fix metadata descriptions

---

.github/workflows/deploy.yml
.github/workflows/sync-submodules.yml

CI isn't running for BlueOS-deploy. Hopefully this will make it run on schedule, or at least be manually triggerable from workflow dispatch.

workflows: fix CI - restore Sync Submodules

---

additional/sonars/index.md
recommended/tether-interface/index.md

- Fixes #68 
- Fixes #101 
⚠️ Only merge if #108 and #109 are accepted (otherwise these changes need to be duplicated individually to the `main` and `BlueOS-deploy` branches)

Hardware extra content

---

_index.md
installation.md

We may wish to wait for stable to be released before we merge this, since it removes the "beta" designation when entering the 1.1 docs, but I'm not too fussed either way.
The "Latest Stable" shield link automatically tracks our latest (non pre-release) release tag, so will fix itself once 1.1 is released :-)

[BlueOS-1.1] Update for stable

---

.github/workflows/check-trailing-spaces.yml
.gitmodules
content/software/control-station/_index.md

Add Cockpit docs at `https://docs.bluerobotics.com/ardusub-zola/software/control-station/Cockpit-0.0`.

[main] add initial Cockpit docs

---

installation.md

Pointed out by G. that the 1.0 docs still only display the 1.0 release.
We should also have a banner or something for docs that aren't the latest stable version, but that can be handled in a separate PR.

installation: make version self-updating

---

.gitmodules
content/_index.md
content/extensions/_index.md
content/extensions/cockpit/_index.md

Adds Cockpit docs to `https://blueos.cloud/docs/extensions/cockpit/0.0`.
I'm a bit unsure whether we want to include this here (since it then opens the door to other extensions being documented in the BlueOS docs), or if Cockpit will have its own website where its docs can be hosted.

[BlueOS-deploy] Add initial Cockpit docs

---

advanced-usage/index.md
development/bootstrap/index.md
getting-started/index.md

Some small improvements.
Most of them can be back-ported to `BlueOS-1.1` and `BlueOS-beta` immediately, but the mDNS docs can't because [the USB-OTG fix](https://github.com/bluerobotics/BlueOS/pull/2150) is currently only in the `master` branch of BlueOS (it hasn't been ported to `1.1` yet, and isn't yet in a beta release).

[BlueOS-devel] improve various docs

---

.gitmodules

`Cockpit-0.0` was only relevant while in alpha - we don't actually want docs for it. Now that the 1.0 beta is released, switch to using `Cockpit-1.0` instead.

[main] `Cockpit-0.0` -> `Cockpit-1.0`

---

.gitmodules

`Cockpit-0.0` was only relevant while in alpha - we don't actually want docs for it. Now that the 1.0 beta is released, switch to using `Cockpit-1.0` instead.

[BlueOS-deploy] `cockpit/0.0` -> `cockpit/1.0`

---

config.toml
templates/base.html

We could add such change on the official template as well

Add site verification

---

development/extensions/index.md

Avoids new branches trying to take a redirect that's owned by `BlueOS-1.1`.
Multiple destinations for the same redirect cause Zola building to fail.

[BlueOS-devel] development: extensions: remove unused redirect

---

development/extensions/index.md

Avoids new branches trying to take a redirect that's owned by `BlueOS-1.1`.
Multiple destinations for the same redirect cause Zola building to fail.

[BlueOS-beta] development: extensions: remove unused redirect

---

development/extensions/index.md

Avoids new branches trying to take a redirect that's owned by `BlueOS-1.1`.
Multiple destinations for the same redirect cause Zola building to fail.

[BlueOS-1.2] development: extensions: remove unused redirect
